"""dodanie tagow

Revision ID: ffa1eed35fc2
Revises: 1f55be20d791
Create Date: 2026-08-26 21:13:26.304320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa1eed35fc2'
down_revision: Union[str, Sequence[str], None] = '1f55be20d791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('zadania_tagi',
    sa.Column('zadanie_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tagi.id'], ),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadania.id'], ),
    sa.PrimaryKeyConstraint('zadanie_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania_tagi')
    op.drop_table('tagi')
    # ### end Alembic commands ###
